# Generated by Django 4.2.11 on 2024-04-27 13:58

import django.core.files.storage
from django.db import migrations, models
import profilapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('profilapp', '0002_folder_is_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='is_root',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=1, storage=django.core.files.storage.FileSystemStorage(base_url='/profil/', location='profil')),
            preserve_default=False,
        ),
    ]
