# Generated by Django 4.2.11 on 2024-04-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilapp', '0003_remove_folder_is_root_file_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
    ]
