# Generated by Django 4.2.11 on 2024-04-28 08:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilapp', '0004_alter_folder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/profil/', location='profil/'), upload_to='uploads/'),
        ),
    ]
